---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebpf-playground
  labels:
    app: ebpf-playground
spec:
  selector:
    matchLabels:
      app: ebpf-playground
  replicas: 1
  template:
    metadata:
      labels:
        app: ebpf-playground
    spec:
      initContainers:
      - name: ebpf-generate
        image: quay.io/thejasn/ebpf-playground:latest
        command: ['sh', '-c', "make generate && cd /src/ebpf && go build -o /main ./cmd/main.go"]    
      containers:
      - image: quay.io/thejasn/ebpf-playground:latest
        name: ebpf-playground
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - name: ebpf-script
            mountPath: /src/ebpf/pgm/ebpc.c
          - name: go-ebpf-script
            mountPath: /src/ebpf/pgm/ebpc.go
      volumes:
      - name: ebpf-script
        configMap:
          name: ebpf-script
      - name: go-ebpf-script
        configMap:
          name: go-ebpf-script        


